/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Kellman N. Gunawan
 */
public class kategori extends javax.swing.JFrame {

    /**
     * Creates new form kategori
     */
    public kategori() { //method kategori
        initComponents(); //initcomponents
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        psikotropika = new javax.swing.JButton();
        narkotika = new javax.swing.JButton();
        bebas = new javax.swing.JButton();
        keras = new javax.swing.JButton();
        input = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SILAKAN PILIH KATEGORI OBAT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 60));

        psikotropika.setBackground(new java.awt.Color(255, 0, 0));
        psikotropika.setText("Psikotropika");
        psikotropika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psikotropikaActionPerformed(evt);
            }
        });
        getContentPane().add(psikotropika, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 120, 41));

        narkotika.setBackground(new java.awt.Color(255, 0, 0));
        narkotika.setText("Narkotika");
        narkotika.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                narkotikaActionPerformed(evt);
            }
        });
        getContentPane().add(narkotika, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 91, 122, 41));

        bebas.setBackground(new java.awt.Color(255, 0, 0));
        bebas.setText("Bebas");
        bebas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bebasActionPerformed(evt);
            }
        });
        getContentPane().add(bebas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 119, 37));

        keras.setBackground(new java.awt.Color(255, 0, 0));
        keras.setText("Keras");
        keras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kerasActionPerformed(evt);
            }
        });
        getContentPane().add(keras, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 122, 37));

        input.setBackground(new java.awt.Color(255, 0, 0));
        input.setText("input data");
        input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputActionPerformed(evt);
            }
        });
        getContentPane().add(input, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 120, 39));

        kembali.setBackground(new java.awt.Color(255, 0, 0));
        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 120, 40));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kategorijpg.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 0, 470, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void psikotropikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psikotropikaActionPerformed
        // TODO add your handling code here:
        new psikotropika().setVisible(true); //tombol ke form psikotropika
        dispose();
    }//GEN-LAST:event_psikotropikaActionPerformed

    private void narkotikaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_narkotikaActionPerformed
        // TODO add your handling code here:
        new narkotika().setVisible(true); //tombol ke form narkotika
        dispose();
    }//GEN-LAST:event_narkotikaActionPerformed

    private void bebasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bebasActionPerformed
        // TODO add your handling code here:
        new bebas().setVisible(true); //tombol ke form bebas
        dispose();
    }//GEN-LAST:event_bebasActionPerformed

    private void kerasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kerasActionPerformed
        // TODO add your handling code here:
        new keras().setVisible(true); //tombol ke form keras
        dispose();
    }//GEN-LAST:event_kerasActionPerformed

    private void inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputActionPerformed
        // TODO add your handling code here:
        new input().setVisible(true); //tombol ke form input
        dispose();
    }//GEN-LAST:event_inputActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        new Menu().setVisible(true);//tombol ke form menu
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bebas;
    private javax.swing.JButton input;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton kembali;
    private javax.swing.JButton keras;
    private javax.swing.JButton narkotika;
    private javax.swing.JButton psikotropika;
    // End of variables declaration//GEN-END:variables
}
