/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;// Mengimport java.sql.Connection untuk koneksi ke Database
import java.sql.ResultSet;// Mengimport java.sql.ResultSet untuk dapat menampilkan/memilih data di Database 
import java.sql.Statement;// Mengimport java.sql.Statement untuk menggunakan perintah SQL (Insert Update Delete) ke Database
import javax.swing.JOptionPane;// Mengimport javax.swing.JOptionPane untuk menggunakan fitur JOptionPane
import model.koneksi;// mengimport package model class koneksi untuk mengimport seluruh kodingan di dalamnya

/**
 *
 * @author Kellman N. Gunawan
 */
public class login extends javax.swing.JFrame {
    String user, pass, sql;// Mendeklarasikan variable Username, Password, dan sql
    Connection con;// Membuat variable con sebagai perwakilan objek Connection
    Statement stm;// Membuat variable  stm sebagai perwakilan objek Statement 
    ResultSet rs;// Membuat variable rs sebagai perwakilan objek ResultSet

    /**
     * Creates new form login
     */
    public login() {// Method Login 
        initComponents();// Menginisialisasi Components
        koneksi DB = new koneksi();// Membuat objek DB untuk kelas Koneksi
        DB.koneksi();// Memanggil method koneksi pada kelas Koneksi melalui objek DB
        con = DB.con;// Menyamakan variable con di kelas Aplikasi_Kasir dengan con di kelas Koneksi
        stm = (Statement) DB.stm;// Menyamakan variable stm di kelas Aplikasi_Kasir dengan stm di kelas Koneksi
    }
    public void clear(){// method clean yang digunakan untuk mengosongkan txtPassword dan txtUsername
        username.setText("");//membuat isi username kosong
        password.setText("");//membuat isi password ke kosong
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        signup = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        login = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGIN");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 460, 60));

        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 205, -1));

        signup.setBackground(new java.awt.Color(255, 0, 0));
        signup.setText("sign up");
        signup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupActionPerformed(evt);
            }
        });
        getContentPane().add(signup, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, 50));

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setText("exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 290, 70, 50));

        login.setBackground(new java.awt.Color(255, 0, 0));
        login.setForeground(new java.awt.Color(51, 0, 51));
        login.setText("login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 290, 80, 50));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 205, -1));

        jTextField1.setBackground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 60));

        jTextField2.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 110, 40));

        jTextField3.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 110, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/penggunajpg.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 460, 320));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupActionPerformed
        new signup().setVisible(true);//pindah form ke form signup
        dispose();
    }//GEN-LAST:event_signupActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
       
        try{
            user = username.getText(); //menampung username ke user
            pass = password.getText(); //menampung password ke pass
           
            sql = "SELECT * FROM tblogin WHERE username='"+user+"' AND password='"+pass+"'"; // Perintah untuk menampilkan data pada Database tblogin 
            rs = stm.executeQuery(sql);// Mendefinisikan untuk mendapatkan data dari hasil Query
            if(rs.next()){// Kondisi if next
                if(user.equals(rs.getString("username")) && pass.equals(rs.getString("password"))){ // kondisi if txtUsername equals string username dan txtPassword equals string password
                    JOptionPane.showMessageDialog(null, "Anda Berhasil Login/Login Successful!");// Menampilkan GUI Message "Berhasil Login"
                    new Menu().setVisible(true);// Ketika user menekan Login button maka akan diarahkan ke frame menu
                    this.setVisible(false);
                }
            }    
            sql = "SELECT * FROM tblsignup WHERE username='"+user+"' AND password='"+pass+"'";// Perintah untuk menampilkan data pada Database tbsignup
            rs = stm.executeQuery(sql);// Mendefinisikan untuk mendapatkan data dari hasil Query
            if(rs.next()){// Kondisi if next
                if(user.equals(rs.getString("username")) && pass.equals(rs.getString("password"))){ // kondisi if txtUsername equals string username dan txtPassword equals string password
                    JOptionPane.showMessageDialog(null, "Anda Berhasil Login/Login Successful!");// Menampilkan GUI Message "Berhasil Login"
                    new Menu().setVisible(true);// Ketika user menekan Login button maka akan diarahkan ke frame menu
                    this.setVisible(false);
                }
            }
            
        } catch (Exception e){// Statement catch untuk menangkap error Exception
            JOptionPane.showMessageDialog(null, e.getMessage());// Menampilkan GUI Message
        }
    }//GEN-LAST:event_loginActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);//keluar program
    }//GEN-LAST:event_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton signup;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
