/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;// Mengimport java.sql.Connection untuk koneksi ke Database
import java.sql.ResultSet;// Mengimport java.sql.ResultSet untuk dapat menampilkan/memilih data di Database 
import java.sql.SQLException;// Mengimport java.sql.Statement untuk menggunakan perintah SQL (Insert Update Delete) ke Database
import java.sql.Statement;// Mengimport java.sql.Statement untuk menggunakan perintah SQL (Insert Update Delete) ke Database
import java.util.logging.Level;// Mengimport java.sql.Statement untuk menggunakan perintah SQL (Insert Update Delete) ke Database
import java.util.logging.Logger;// Mengimport java.sql.Statement untuk menggunakan perintah SQL (Insert Update Delete) ke Database
import javax.swing.JOptionPane;// Mengimport java.sql.Statement untuk menggunakan perintah SQL (Insert Update Delete) ke Database
import model.koneksi;// mengimport package model class koneksi untuk mengimport seluruh kodingan di dalamnya

/**
 *
 * @author Kellman N. Gunawan
 */
public class signup extends javax.swing.JFrame {// Sebuah public class SignUp yang meng extend javax.swing.JFrame


    /**
     * Creates new form signup
     */
    
    String user, pass, repass;// Mendeklarasikan variable user, Password, RePassword, Fullname bertipe data string
    int panjanguser = 50;// Mendeklarasikan variable P_User bertipe data integer dengan inisialisasi 50
    
    Connection con;// Membuat variable con sebagai perwakilan objek Connection 
    Statement stm;// Membuat variable  stm sebagai perwakilan objek Statement 
    ResultSet rs;// Membuat variable rs sebagai perwakilan objek ResultSet    
    
    public signup() {// Method SignUp
        initComponents();// Menginisialisasi Components
        koneksi DB = new koneksi();// Membuat objek DB untuk kelas Koneksi
        DB.koneksi();// Memanggil method koneksi pada kelas Koneksi melalui objek DB
        con = DB.con;// Menyamakan variable con di kelas Aplikasi_Kasir dengan con di kelas Koneksi
        stm = (Statement) DB.stm;        // Menyamakan variable stm di kelas Aplikasi_Kasir dengan stm di kelas Koneksi
    }
    public void clear(){// Method clean yang digunakan untuk megosongkan txtFullname, txtPassword, txtRePassword, txtUsername
        username.setText("");
        password.setText("");
        repassword.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        save = new javax.swing.JButton();
        password = new javax.swing.JPasswordField();
        repassword = new javax.swing.JPasswordField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 87, -1));

        jLabel3.setText("password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 87, -1));

        jLabel4.setText("re-password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 193, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("SIGN UP");
        jLabel5.setAutoscrolls(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 540, 70));

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setText("LOGIN");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, 41));

        save.setBackground(new java.awt.Color(255, 0, 0));
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        getContentPane().add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 300, 80, 41));
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 193, -1));

        repassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repasswordActionPerformed(evt);
            }
        });
        getContentPane().add(repassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 193, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 0, 51));
        jTextField1.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 70));

        jTextField2.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 100, 40));

        jTextField3.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 100, 40));

        jLabel6.setText("username");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 87, -1));

        jTextField5.setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/signupjpg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        new login().setVisible(true);//ke form login
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        pass = password.getText();// Menginisialisasi variable Password dengan txtPassword.getText()
        repass = repassword.getText();// Menginisialisasi variable RePassword dengan txtRePassword.getText()
        panjanguser = username.getText().length();// Menginisialisasi variable P_User dengan txtUsername.getText().length()
        
        try {// Statement try
            if (repass.equals(pass) && panjanguser>=2) {// kondisi if RePassword equals Password dan P_User lebih dari sama dengan 2
                stm.executeUpdate("insert into tblsignup values ("
                        + "'" + username.getText() + "',"
                        + "'" + String.valueOf(password.getPassword()) + "',"
                        + "'" + String.valueOf(repassword.getPassword()) + "')"// Melakukan update pada Database tbsignup
                );
                {
                    JOptionPane.showMessageDialog(null, "Save Succesfull");// Menampilkan GUI Message "Save Succesfull"
                }
                clear();// Memanggil method clean()
            } else {
                JOptionPane.showMessageDialog(null, "Access Denied");// Menampilkan GUI Message "Access Denied"
                clear();// Memanggil method clean()
            };
        } catch (Exception e) {// Statement catch untuk menangkap error exception
            JOptionPane.showMessageDialog(this, e.getMessage()); // Menampilkan GUI Message
        }
    }//GEN-LAST:event_saveActionPerformed

    private void repasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repasswordActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField repassword;
    private javax.swing.JButton save;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
